# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cvimg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cvimg.proto',
  package='cvimg',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x63vimg.proto\x12\x05\x63vimg\"\x0e\n\x0c\x63vimgRequest\"+\n\rcvimgResponse\x12\x0c\n\x04meta\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x32H\n\x0c\x63vimgService\x12\x38\n\tSendImage\x12\x13.cvimg.cvimgRequest\x1a\x14.cvimg.cvimgResponse\"\x00\x62\x06proto3'
)




_CVIMGREQUEST = _descriptor.Descriptor(
  name='cvimgRequest',
  full_name='cvimg.cvimgRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=36,
)


_CVIMGRESPONSE = _descriptor.Descriptor(
  name='cvimgResponse',
  full_name='cvimg.cvimgResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='meta', full_name='cvimg.cvimgResponse.meta', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='cvimg.cvimgResponse.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['cvimgRequest'] = _CVIMGREQUEST
DESCRIPTOR.message_types_by_name['cvimgResponse'] = _CVIMGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

cvimgRequest = _reflection.GeneratedProtocolMessageType('cvimgRequest', (_message.Message,), {
  'DESCRIPTOR' : _CVIMGREQUEST,
  '__module__' : 'cvimg_pb2'
  # @@protoc_insertion_point(class_scope:cvimg.cvimgRequest)
  })
_sym_db.RegisterMessage(cvimgRequest)

cvimgResponse = _reflection.GeneratedProtocolMessageType('cvimgResponse', (_message.Message,), {
  'DESCRIPTOR' : _CVIMGRESPONSE,
  '__module__' : 'cvimg_pb2'
  # @@protoc_insertion_point(class_scope:cvimg.cvimgResponse)
  })
_sym_db.RegisterMessage(cvimgResponse)



_CVIMGSERVICE = _descriptor.ServiceDescriptor(
  name='cvimgService',
  full_name='cvimg.cvimgService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=83,
  serialized_end=155,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendImage',
    full_name='cvimg.cvimgService.SendImage',
    index=0,
    containing_service=None,
    input_type=_CVIMGREQUEST,
    output_type=_CVIMGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CVIMGSERVICE)

DESCRIPTOR.services_by_name['cvimgService'] = _CVIMGSERVICE

# @@protoc_insertion_point(module_scope)
